CUDA_VISIBLE_DEVICES=0 \
python train.py \
--train_img_A_path data/monet2photo/trainA/ \
--train_img_B_path data/monet2photo/trainB/ \
--test_img_A_path data/monet2photo/testA/ \
--test_img_B_path data/monet2photo/testB/ \
--input_transform flip \
--experiment_name monet2photo \
--batch_size 16 \
--image_size 256 \
--model_type cyclegan \
--kernel_size 4 \
--mse_loss_weight 10. \
--mse_loss_type l1 \
--gen_num_channels 32 \
--gen_max_channels 128 \
--gen_latent_size 64 \
--gen_num_res_blocks 9 \
--gen_norm_layer none \
--get_upsampling_layer conv_transpose \
--dis_input_sizes 256,128,64,32,16 \
--dis_input_num_channels 64,128,256,512,512 \
--dis_output_sizes 16,8 \
--dis_num_channels 64 \
--dis_max_channels 128 \
--dis_adv_loss_type lsgan \
--dis_use_encoder \
--dis_kernel_size_io 3 \
--enc_type vgg19_pytorch \
--num_epoch 50 \
--epoch_len 1000 \
--pretrained_gen_path runs/monet2photo_pretrain/checkpoints/